import '../styles/mordern-normalize.css';
import '../styles/style.css';
import '../styles/hero.css';
import '../styles/processo.css';
import '../styles/servicos.css';
import '../styles/footer.css';
import '../src/stickNavMenu.js';
import '../styles/hamburguer-menu.css';
import '../styles/portifolio.css';
